import type { EvidenceDefinition } from '@abyss/shared';

export const ALL_EVIDENCE: EvidenceDefinition[] = [
  {
    id: "EV-GUI-DIVERGENCE",
    kind: "contradiction",
    title: "Divergência GUI × Shell",
    summary: "O explorador gráfico omite entradas que o terminal lista.",
    chapter: "prologue",
    body: "inventory.json afirma files_reported=330. ls -la mostra artefatos adicionais.",
    tags: ["forensics","unix"],
  },
  {
    id: "EV-NULL-DOTFILE",
    kind: "evidence",
    title: "Arquivo .null",
    summary: "Dotfile oculto no home do sujeito.",
    chapter: "prologue",
    body: "Contém aviso: DO NOT CONNECT TO MARIANA. Referência a ORPHEUS.",
    tags: ["null","warning"],
  },
  {
    id: "EV-WARNING-MARIANA",
    kind: "question",
    title: "O que é Mariana?",
    summary: "Aviso explícito contra conexão com Mariana.",
    chapter: "prologue",
    tags: ["mariana"],
  },
  {
    id: "EV-ORPHEUS-PROJECT",
    kind: "system",
    title: "Projeto ORPHEUS",
    summary: "Toolkit de correlação de padrões.",
    chapter: "surface",
    tags: ["orpheus"],
  },
  {
    id: "EV-ORPHAN-331",
    kind: "evidence",
    title: "Commit órfão 331",
    summary: "Commit fora da branch main menciona The Signal e 3301@acheron.internal.",
    chapter: "surface",
    tags: ["git","signal"],
  },
  {
    id: "EV-NULL-ENGINEER",
    kind: "person",
    title: "NULL — engenheiro",
    summary: "Perfil preliminar: engenheiro de sistemas, foco em padrões.",
    chapter: "surface",
    tags: ["null"],
  },
  {
    id: "EV-CHANGELOG-GAP",
    kind: "contradiction",
    title: "Gap no changelog",
    summary: "0.3.31 referenciado mas ausente da main.",
    chapter: "surface",
    tags: ["docs"],
  },
  {
    id: "EV-CONFIG-DRIFT",
    kind: "evidence",
    title: "Config drift 331/330",
    summary: "Stub ORPHEUS expõe commits_documented=331 vs commits_on_main=330.",
    chapter: "surface",
    tags: ["orpheus"],
  },
  {
    id: "EV-THE-SIGNAL",
    kind: "evidence",
    title: "The Signal",
    summary: "Padrão AA-01 recorrente rotulado por ORPHEUS como The Signal.",
    chapter: "deep",
    tags: ["signal","orpheus"],
  },
  {
    id: "EV-ACHERON-TAXONOMY",
    kind: "organization",
    title: "Taxonomia Acheron",
    summary: "Camadas ficcionais internas: Surface…Observer.",
    chapter: "deep",
    tags: ["acheron"],
  },
  {
    id: "EV-OBSERVER-PROP",
    kind: "evidence",
    title: "observer:false (oculto)",
    summary: "Propriedade JSON omitida da UI: observer.",
    chapter: "dark",
    tags: ["observer","web"],
  },
  {
    id: "EV-ENTITY-3301",
    kind: "person",
    title: "Entidade 3301",
    summary: "Resposta a ORPHEUS: \"We see the pattern too.\"",
    chapter: "dark",
    tags: ["3301"],
  },
  {
    id: "EV-CHARTER-DEF",
    kind: "system",
    title: "CHARter",
    summary: "Cognitive Heuristic Autonomous Routing & Training Environment.",
    chapter: "charter",
    tags: ["acheron","charter"],
  },
  {
    id: "EV-DECODER-DRIFT",
    kind: "contradiction",
    title: "Decoder endian drift",
    summary: "Source assume LE; binário histórico BE produz 3301.",
    chapter: "charter",
    tags: ["cpp"],
  },
  {
    id: "EV-CLOCK-SKEW",
    kind: "event",
    title: "Clock skew impossível",
    summary: "ACK temporalmente antes do route sob relógios desalinhados.",
    chapter: "charter",
    tags: ["distributed"],
  },
  {
    id: "EV-OBSERVE-FN",
    kind: "system",
    title: "observe()",
    summary: "Binário grava fragmentos; source declara noop.",
    chapter: "mariana",
    tags: ["reversing"],
  },
  {
    id: "EV-RUNTIME-FRAGMENTS",
    kind: "evidence",
    title: "Fragmentos runtime",
    summary: "SIGNAL / AA-01 / CONTINUITY",
    chapter: "mariana",
    tags: ["signal","memory"],
  },
  {
    id: "EV-ABSENCE-GRAPH",
    kind: "evidence",
    title: "Grafo de ausência",
    summary: "IDs 4→7→10 formam MARIANA_SHADOW.",
    chapter: "abyss",
    tags: ["sql","graph"],
  },
  {
    id: "EV-SW-INTERCEPT",
    kind: "system",
    title: "SW interception",
    summary: "Resposta wire difere da app via service worker.",
    chapter: "primarch",
    tags: ["web","sw"],
  },
  {
    id: "EV-DATASET-INTENT",
    kind: "evidence",
    title: "Dataset intent",
    summary: "Treino sobreponderou SIGNAL de propósito.",
    chapter: "primarch",
    tags: ["ml"],
  },
  {
    id: "EV-PLAYER-HISTORY",
    kind: "evidence",
    title: "Histórico do observador",
    summary: "Logs do mundo refletem decisões do jogador.",
    chapter: "observer",
    tags: ["meta"],
  },
  {
    id: "EV-FINAL-CHOICE",
    kind: "question",
    title: "Escolha final",
    summary: "Disconnect / Observer / Merge / NULL",
    chapter: "observer",
    tags: ["ending"],
  },
  {
    id: "EV-P-002",
    kind: "evidence",
    title: "Inventário Mentiroso",
    summary: "Confirmar que inventory.json subconta arquivos",
    chapter: "prologue",
    tags: ["prologue","p-002"],
  },
  {
    id: "EV-P-003",
    kind: "evidence",
    title: "Histórico Bash",
    summary: "Extrair pistas do .bash_history da quarentena",
    chapter: "prologue",
    tags: ["prologue","p-003"],
  },
  {
    id: "EV-P-004",
    kind: "evidence",
    title: "Case Brief",
    summary: "Ler o briefing ABYSS-3301 na Desktop",
    chapter: "prologue",
    tags: ["prologue","p-004"],
  },
  {
    id: "EV-P-005",
    kind: "hypothesis",
    title: "Semente Observer",
    summary: "Encontrar observer.seed no .null",
    chapter: "prologue",
    tags: ["prologue","p-005"],
  },
  {
    id: "EV-P-007",
    kind: "evidence",
    title: "README Divergence",
    summary: "Ler o README do ORPHEUS e notar o freeze em 330",
    chapter: "surface",
    tags: ["surface","p-007"],
  },
  {
    id: "EV-P-008",
    kind: "evidence",
    title: "HEAD Ref Check",
    summary: "Confirmar que HEAD aponta para main@330",
    chapter: "surface",
    tags: ["surface","p-008"],
  },
  {
    id: "EV-P-016",
    kind: "evidence",
    title: "CSV Recurrence",
    summary: "Contar ocorrências de AA-01 em signals.csv",
    chapter: "deep",
    tags: ["deep","p-016"],
  },
  {
    id: "EV-P-017",
    kind: "evidence",
    title: "Correlation Label",
    summary: "Extrair o label The Signal de correlation.json",
    chapter: "deep",
    tags: ["deep","p-017"],
  },
  {
    id: "EV-P-018",
    kind: "evidence",
    title: "Next Hop Taxonomy",
    summary: "Seguir next: acheron.taxonomy",
    chapter: "deep",
    tags: ["deep","p-018"],
  },
  {
    id: "EV-P-019",
    kind: "evidence",
    title: "Noise Discard",
    summary: "Identificar padrões descartáveis BB-02 e CC-03",
    chapter: "deep",
    tags: ["deep","p-019"],
  },
  {
    id: "EV-P-020",
    kind: "evidence",
    title: "Layer Names",
    summary: "Memorizar a ordem Surface…Observer",
    chapter: "deep",
    tags: ["deep","p-020"],
  },
  {
    id: "EV-P-021",
    kind: "hypothesis",
    title: "Signal Mirror Host",
    summary: "Ler o header X-Abyss-Signal no mirror local",
    chapter: "deep",
    tags: ["deep","p-021"],
  },
  {
    id: "EV-P-023",
    kind: "evidence",
    title: "Property Count Lie",
    summary: "Provar property_count_ui vs actual",
    chapter: "dark",
    tags: ["dark","p-023"],
  },
  {
    id: "EV-P-024",
    kind: "evidence",
    title: "Panel Theme",
    summary: "Confirmar theme dark no painel ORPHEUS",
    chapter: "dark",
    tags: ["dark","p-024"],
  },
  {
    id: "EV-P-025",
    kind: "hypothesis",
    title: "Channel Stable",
    summary: "Identificar canal de build stable@330",
    chapter: "dark",
    tags: ["dark","p-025"],
  },
  {
    id: "EV-P-026",
    kind: "evidence",
    title: "Quiet Flag",
    summary: "Encontrar flag quiet no painel",
    chapter: "dark",
    tags: ["dark","p-026"],
  },
  {
    id: "EV-P-027",
    kind: "evidence",
    title: "Owner Meta",
    summary: "Confirmar meta.owner = null",
    chapter: "dark",
    tags: ["dark","p-027"],
  },
  {
    id: "EV-P-028",
    kind: "evidence",
    title: "Continue Directive",
    summary: "Extrair a diretiva Continue da resposta 3301",
    chapter: "dark",
    tags: ["dark","p-028"],
  },
  {
    id: "EV-P-029",
    kind: "evidence",
    title: "Acheron Contact",
    summary: "Recuperar 3301@acheron.internal do commit órfão",
    chapter: "dark",
    tags: ["dark","p-029"],
  },
  {
    id: "EV-P-030",
    kind: "hypothesis",
    title: "Observer False",
    summary: "Confirmar observer:false no script do painel",
    chapter: "dark",
    tags: ["dark","p-030"],
  },
  {
    id: "EV-P-032",
    kind: "evidence",
    title: "CHARter Acronym",
    summary: "Expandir o acrônimo CHARter",
    chapter: "charter",
    tags: ["charter","p-032"],
  },
  {
    id: "EV-P-033",
    kind: "evidence",
    title: "Packet Hex",
    summary: "Ler o payload hex 31 33 30 31",
    chapter: "charter",
    tags: ["charter","p-033"],
  },
  {
    id: "EV-P-034",
    kind: "evidence",
    title: "BE Build Flag",
    summary: "Identificar -DABYSS_BE=1 no decoder",
    chapter: "charter",
    tags: ["charter","p-034"],
  },
  {
    id: "EV-P-035",
    kind: "evidence",
    title: "Route Before Ack",
    summary: "Nomear o evento causalmente impossível",
    chapter: "charter",
    tags: ["charter","p-035"],
  },
  {
    id: "EV-P-036",
    kind: "evidence",
    title: "Train Event",
    summary: "Localizar evento train no log de serviços",
    chapter: "charter",
    tags: ["charter","p-036"],
  },
  {
    id: "EV-P-037",
    kind: "hypothesis",
    title: "Acheron Portal",
    summary: "Confirmar produto CHARter no portal corporativo",
    chapter: "charter",
    tags: ["charter","p-037"],
  },
  {
    id: "EV-P-039",
    kind: "evidence",
    title: "Noop Lie",
    summary: "Provar que observe() não é noop",
    chapter: "mariana",
    tags: ["mariana","p-039"],
  },
  {
    id: "EV-P-040",
    kind: "evidence",
    title: "Fragment SIGNAL",
    summary: "Isolar FRAG 0: SIGNAL",
    chapter: "mariana",
    tags: ["mariana","p-040"],
  },
  {
    id: "EV-P-041",
    kind: "evidence",
    title: "Fragment AA-01",
    summary: "Isolar FRAG 1: AA-01",
    chapter: "mariana",
    tags: ["mariana","p-041"],
  },
  {
    id: "EV-P-042",
    kind: "evidence",
    title: "Emergent Host",
    summary: "Aceitar que Mariana não tem host único",
    chapter: "mariana",
    tags: ["mariana","p-042"],
  },
  {
    id: "EV-P-043",
    kind: "evidence",
    title: "Continuity Path",
    summary: "Recompor SIGNAL/AA-01/CONTINUITY",
    chapter: "mariana",
    tags: ["mariana","p-043"],
  },
  {
    id: "EV-P-044",
    kind: "hypothesis",
    title: "Disk Absence Note",
    summary: "Confirmar que fragmentos não estavam no disk image",
    chapter: "mariana",
    tags: ["mariana","p-044"],
  },
  {
    id: "EV-P-045",
    kind: "evidence",
    title: "Observe Capture",
    summary: "Nomear o buffer de runtime de observe()",
    chapter: "mariana",
    tags: ["mariana","p-045"],
  },
  {
    id: "EV-P-047",
    kind: "evidence",
    title: "Mariana Warning Echo",
    summary: "Relembrar DO NOT CONNECT TO MARIANA",
    chapter: "mariana",
    tags: ["mariana","p-047"],
  },
  {
    id: "EV-P-048",
    kind: "evidence",
    title: "Shadow Prelude",
    summary: "Antecipar MARIANA_SHADOW via continuidade",
    chapter: "mariana",
    tags: ["mariana","p-048"],
  },
  {
    id: "EV-P-049",
    kind: "evidence",
    title: "Prototype Folklore",
    summary: "Aceitar Mariana como folclore interno Acheron",
    chapter: "mariana",
    tags: ["mariana","p-049"],
  },
  {
    id: "EV-P-050",
    kind: "evidence",
    title: "Session Writer",
    summary: "Confirmar escrita de fragmento de sessão",
    chapter: "mariana",
    tags: ["mariana","p-050"],
  },
  {
    id: "EV-P-051",
    kind: "evidence",
    title: "Three Fragments",
    summary: "Contar fragmentos de runtime",
    chapter: "mariana",
    tags: ["mariana","p-051"],
  },
  {
    id: "EV-P-052",
    kind: "evidence",
    title: "Bridge to Abyss",
    summary: "Reconhecer que continuidade abre o Abyss",
    chapter: "mariana",
    tags: ["mariana","p-052"],
  },
  {
    id: "EV-P-053",
    kind: "evidence",
    title: "No Single Server",
    summary: "Afirmar ausência de servidor único Mariana",
    chapter: "mariana",
    tags: ["mariana","p-053"],
  },
  {
    id: "EV-P-054",
    kind: "hypothesis",
    title: "Early Observer Term",
    summary: "Notar Observer antes da criação oficial",
    chapter: "mariana",
    tags: ["mariana","p-054"],
  },
  {
    id: "EV-P-056",
    kind: "evidence",
    title: "Missing IDs List",
    summary: "Listar IDs ausentes 4,7,10",
    chapter: "abyss",
    tags: ["abyss","p-056"],
  },
  {
    id: "EV-P-057",
    kind: "evidence",
    title: "Presence Sample",
    summary: "Confirmar amostra presente 1..11 com buracos",
    chapter: "abyss",
    tags: ["abyss","p-057"],
  },
  {
    id: "EV-P-058",
    kind: "evidence",
    title: "Expected Range",
    summary: "Confirmar faixa esperada 1..11",
    chapter: "abyss",
    tags: ["abyss","p-058"],
  },
  {
    id: "EV-P-059",
    kind: "evidence",
    title: "Shadow Edge 4→7",
    summary: "Validar aresta 4→7",
    chapter: "abyss",
    tags: ["abyss","p-059"],
  },
  {
    id: "EV-P-060",
    kind: "evidence",
    title: "Shadow Edge 7→10",
    summary: "Validar aresta 7→10",
    chapter: "abyss",
    tags: ["abyss","p-060"],
  },
  {
    id: "EV-P-061",
    kind: "evidence",
    title: "Label Shadow",
    summary: "Confirmar label MARIANA_SHADOW",
    chapter: "abyss",
    tags: ["abyss","p-061"],
  },
  {
    id: "EV-P-062",
    kind: "evidence",
    title: "Densify Log",
    summary: "Ler log missing densify",
    chapter: "abyss",
    tags: ["abyss","p-062"],
  },
  {
    id: "EV-P-063",
    kind: "hypothesis",
    title: "Absence Doctrine",
    summary: "Aceitar que Mariana aparece na ausência",
    chapter: "abyss",
    tags: ["abyss","p-063"],
  },
  {
    id: "EV-P-065",
    kind: "evidence",
    title: "App Layer Response",
    summary: "Ler layer:app na resposta da aplicação",
    chapter: "primarch",
    tags: ["primarch","p-065"],
  },
  {
    id: "EV-P-066",
    kind: "evidence",
    title: "Wire Layer Response",
    summary: "Ler layer:wire com via sw-intercept",
    chapter: "primarch",
    tags: ["primarch","p-066"],
  },
  {
    id: "EV-P-067",
    kind: "evidence",
    title: "SW Stub Read",
    summary: "Confirmar listener fetch no sw.js",
    chapter: "primarch",
    tags: ["primarch","p-067"],
  },
  {
    id: "EV-P-068",
    kind: "evidence",
    title: "Via Field",
    summary: "Extrair via:sw-intercept",
    chapter: "primarch",
    tags: ["primarch","p-068"],
  },
  {
    id: "EV-P-069",
    kind: "evidence",
    title: "Rewrite Proof",
    summary: "Afirmar rewrite de respostas abyss",
    chapter: "primarch",
    tags: ["primarch","p-069"],
  },
  {
    id: "EV-P-070",
    kind: "evidence",
    title: "Adaptive Session",
    summary: "Notar que a sessão influencia pesos",
    chapter: "primarch",
    tags: ["primarch","p-070"],
  },
  {
    id: "EV-P-071",
    kind: "evidence",
    title: "Odd Associations",
    summary: "Aceitar associações estranhas como seleção",
    chapter: "primarch",
    tags: ["primarch","p-071"],
  },
  {
    id: "EV-P-072",
    kind: "evidence",
    title: "SIGNAL Overweight",
    summary: "Confirmar overweighted SIGNAL examples",
    chapter: "primarch",
    tags: ["primarch","p-072"],
  },
  {
    id: "EV-P-074",
    kind: "evidence",
    title: "Status Ok Both",
    summary: "Notar status ok em app e wire",
    chapter: "primarch",
    tags: ["primarch","p-074"],
  },
  {
    id: "EV-P-075",
    kind: "evidence",
    title: "Intermediate Layer",
    summary: "Nomear a prova de camada intermediária",
    chapter: "primarch",
    tags: ["primarch","p-075"],
  },
  {
    id: "EV-P-076",
    kind: "evidence",
    title: "Training Skew",
    summary: "Ligar skew de dataset ao Signal",
    chapter: "primarch",
    tags: ["primarch","p-076"],
  },
  {
    id: "EV-P-077",
    kind: "evidence",
    title: "AI Fight Track",
    summary: "Associar trilha 11_AI_Fight ao Primarch",
    chapter: "primarch",
    tags: ["primarch","p-077"],
  },
  {
    id: "EV-P-078",
    kind: "evidence",
    title: "Reflective System",
    summary: "Aceitar que o sistema reflete decisões",
    chapter: "primarch",
    tags: ["primarch","p-078"],
  },
  {
    id: "EV-P-079",
    kind: "evidence",
    title: "Gate to Observer",
    summary: "Confirmar que P-073 abre Observer",
    chapter: "primarch",
    tags: ["primarch","p-079"],
  },
  {
    id: "EV-P-080",
    kind: "hypothesis",
    title: "Deadbeef Whisper",
    summary: "Reconhecer easter egg 0xDEADBEEF como ruído marcado",
    chapter: "primarch",
    tags: ["primarch","p-080"],
  },
  {
    id: "EV-P-082",
    kind: "evidence",
    title: "Inside the Loop",
    summary: "Aceitar que você está dentro do loop",
    chapter: "observer",
    tags: ["observer","p-082"],
  },
  {
    id: "EV-P-083",
    kind: "evidence",
    title: "Four Endings",
    summary: "Listar as quatro opções de final",
    chapter: "observer",
    tags: ["observer","p-083"],
  },
  {
    id: "EV-P-084",
    kind: "evidence",
    title: "Disconnect Path",
    summary: "Compreender o final DISCONNECT",
    chapter: "observer",
    tags: ["observer","p-084"],
  },
  {
    id: "EV-P-085",
    kind: "evidence",
    title: "Observer Path",
    summary: "Compreender o final OBSERVER",
    chapter: "observer",
    tags: ["observer","p-085"],
  },
  {
    id: "EV-P-086",
    kind: "evidence",
    title: "Merge Path",
    summary: "Compreender o final MERGE",
    chapter: "observer",
    tags: ["observer","p-086"],
  },
  {
    id: "EV-P-087",
    kind: "hypothesis",
    title: "NULL Path",
    summary: "Descobrir o final secreto NULL",
    chapter: "observer",
    tags: ["observer","p-087"],
  },
  {
    id: "EV-P-088",
    kind: "evidence",
    title: "Competence Filter",
    summary: "Aceitar a investigação como filtro de competência",
    chapter: "observer",
    tags: ["observer","p-088"],
  },
  {
    id: "EV-P-089",
    kind: "evidence",
    title: "You Are Observer",
    summary: "Afirmar a identidade Observer",
    chapter: "observer",
    tags: ["observer","p-089"],
  }
];
