import type { PuzzleDefinition } from '@abyss/shared';
import { pz, hints } from './helpers.js';

export const ALL_PUZZLES: PuzzleDefinition[] = [
  pz({
    id: 'P-001',
    chapter: 'prologue',
    title: "Hidden File",
    narrativeGoal: "Descobrir o arquivo oculto .null",
    main: true,
    optional: false,
    secret: false,
    prerequisites: [],
    validators: [{"type":"file.exists","path":"/home/null/.null"},{"type":"flag.set","flag":"found.null"}],
    rewards: [{"type":"unlock_flag","flag":"found.null"},{"type":"unlock_evidence","evidenceId":"EV-NULL-DOTFILE"},{"type":"unlock_evidence","evidenceId":"EV-WARNING-MARIANA"},{"type":"unlock_chapter","chapter":"surface"},{"type":"narrative","event":"prologue.complete"}],
    evidenceUnlocks: ["EV-NULL-DOTFILE","EV-WARNING-MARIANA","EV-GUI-DIVERGENCE"],
    hintChain: hints(
      "Inventários gráficos e listagens de sistema nem sempre concordam.",
      "Compare o que o Files mostra em /home/null com o que o Terminal lista com ls -la.",
      "Execute: ls -la /home/null  e então cat /home/null/.null",
    ),
    description: "A GUI reporta 330 arquivos. O shell revela divergência. Encontre o que está escondido.",
    answer: "null",
    answerAliases: [".null","found.null"],
  }),
  pz({
    id: 'P-002',
    chapter: 'prologue',
    title: "Inventário Mentiroso",
    narrativeGoal: "Confirmar que inventory.json subconta arquivos",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"solved.P-002"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-002"},{"type":"unlock_evidence","evidenceId":"EV-P-002"}],
    evidenceUnlocks: ["EV-P-002"],
    hintChain: hints(
      "Números redondos em inventários forenses merecem desconfiança.",
      "Leia Documents/inventory.json e compare com ls -la.",
      "cat ~/Documents/inventory.json | grep files_reported",
    ),
    description: "O inventário GUI afirma 330. Prove a divergência.",
    answer: "330",
  }),
  pz({
    id: 'P-003',
    chapter: 'prologue',
    title: "Histórico Bash",
    narrativeGoal: "Extrair pistas do .bash_history da quarentena",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"solved.P-003"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-003"},{"type":"unlock_evidence","evidenceId":"EV-P-003"}],
    evidenceUnlocks: ["EV-P-003"],
    hintChain: hints(
      "Históricos de shell sobrevivem a sessões e revelam intenções.",
      "Há um .bash_history em /home/null.",
      "cat /home/null/.bash_history",
    ),
    description: "Comandos anteriores apontam para ORPHEUS e inventário.",
    answer: "orpheus",
  }),
  pz({
    id: 'P-004',
    chapter: 'prologue',
    title: "Case Brief",
    narrativeGoal: "Ler o briefing ABYSS-3301 na Desktop",
    main: false,
    optional: true,
    secret: false,
    prerequisites: [],
    validators: [{"type":"flag.set","flag":"solved.P-004"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-004"},{"type":"unlock_evidence","evidenceId":"EV-P-004"}],
    evidenceUnlocks: ["EV-P-004"],
    hintChain: hints(
      "Briefings de caso enquadram o que a interface tenta ocultar.",
      "Desktop/CASE_BRIEF.txt",
      "cat ~/Desktop/CASE_BRIEF.txt",
    ),
    description: "O analista anterior deixou uma nota: confie no shell.",
    answer: "ABYSS-3301",
  }),
  pz({
    id: 'P-005',
    chapter: 'prologue',
    title: "Semente Observer",
    narrativeGoal: "Encontrar observer.seed no .null",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"solved.P-005"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-005"},{"type":"unlock_evidence","evidenceId":"EV-P-005"}],
    evidenceUnlocks: ["EV-P-005"],
    hintChain: hints(
      "Dotfiles às vezes carregam sementes de identidade.",
      "Releia .null com atenção às chaves key/ref.",
      "grep seed /home/null/.null",
    ),
    description: "Uma semente meta está embutida no aviso de Mariana.",
    answer: "observer.seed=0",
  }),
  pz({
    id: 'P-006',
    chapter: 'surface',
    title: "Orphan Commit",
    narrativeGoal: "Encontrar o commit órfão 331 e revelar ORPHEUS",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"found.orpheus"},{"type":"file.contains","path":"/home/null/projects/orpheus/.git/objects/0000000000000000000000000000000000000331","text":"ORPHEUS"}],
    rewards: [{"type":"unlock_flag","flag":"found.orpheus"},{"type":"unlock_app","app":"orpheus"},{"type":"unlock_evidence","evidenceId":"EV-ORPHEUS-PROJECT"},{"type":"unlock_evidence","evidenceId":"EV-ORPHAN-331"},{"type":"unlock_chapter","chapter":"deep"}],
    evidenceUnlocks: ["EV-ORPHEUS-PROJECT","EV-ORPHAN-331","EV-NULL-ENGINEER"],
    hintChain: hints(
      "Documentação e histórico de versão podem divergir de propósito.",
      "Olhe em projects/orpheus — README cita commit 331; a branch main para em 330.",
      "ls projects/orpheus/.git/objects e cat o objeto ...0331",
    ),
    description: "Documentação cita commit 331; a branch main para em 330. Encontre o órfão.",
    answer: "331",
    answerAliases: ["orphan","orpheus","found.orpheus"],
  }),
  pz({
    id: 'P-007',
    chapter: 'surface',
    title: "README Divergence",
    narrativeGoal: "Ler o README do ORPHEUS e notar o freeze em 330",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"solved.P-007"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-007"},{"type":"unlock_evidence","evidenceId":"EV-P-007"}],
    evidenceUnlocks: ["EV-P-007"],
    hintChain: hints(
      "READMEs documentam o estado desejado, não necessariamente o real.",
      "projects/orpheus/README.md",
      "cat ~/projects/orpheus/README.md",
    ),
    description: "O README cita 331 enquanto a main congela em 330.",
    answer: "331",
  }),
  pz({
    id: 'P-008',
    chapter: 'surface',
    title: "HEAD Ref Check",
    narrativeGoal: "Confirmar que HEAD aponta para main@330",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"solved.P-008"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-008"},{"type":"unlock_evidence","evidenceId":"EV-P-008"}],
    evidenceUnlocks: ["EV-P-008"],
    hintChain: hints(
      "Refs Git são a verdade operacional da branch ativa.",
      "Inspecione .git/HEAD e refs/heads/main.",
      "cat ~/projects/orpheus/.git/HEAD && cat ~/projects/orpheus/.git/refs/heads/main",
    ),
    description: "A ref main termina em ...0330.",
    answer: "main",
  }),
  pz({
    id: 'P-009',
    chapter: 'surface',
    title: "Profile Residue",
    narrativeGoal: "Confirmar perfil técnico de NULL",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"read.null.profile"}],
    rewards: [{"type":"unlock_flag","flag":"read.null.profile"},{"type":"unlock_evidence","evidenceId":"EV-NULL-ENGINEER"}],
    evidenceUnlocks: ["EV-NULL-ENGINEER"],
    hintChain: hints(
      "Perfis residuais em Documents frequentemente sobrevivem a limpezas superficiais.",
      "Há um arquivo de perfil em Documents.",
      "cat ~/Documents/null_profile.txt",
    ),
    description: "Há resíduo de perfil em Documents. Confirme quem era NULL.",
    answer: "engenheiro",
    answerAliases: ["null_profile","read.null.profile"],
  }),
  pz({
    id: 'P-010',
    chapter: 'surface',
    title: "Changelog Gap",
    narrativeGoal: "Confirmar gap 330/331 no changelog",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-001"],
    validators: [{"type":"flag.set","flag":"read.changelog.gap"}],
    rewards: [{"type":"unlock_flag","flag":"read.changelog.gap"},{"type":"unlock_evidence","evidenceId":"EV-CHANGELOG-GAP"}],
    evidenceUnlocks: ["EV-CHANGELOG-GAP"],
    hintChain: hints(
      "Changelogs às vezes documentam o que o código não contém.",
      "docs/CHANGELOG.md dentro de orpheus.",
      "cat ~/projects/orpheus/docs/CHANGELOG.md",
    ),
    description: "O changelog documenta 0.3.31 ausente da main.",
    answer: "0.3.31",
    answerAliases: ["331","read.changelog.gap"],
  }),
  pz({
    id: 'P-011',
    chapter: 'surface',
    title: "Config Drift",
    narrativeGoal: "Ver divergência commits_documented vs commits_on_main",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-006"],
    validators: [{"type":"flag.set","flag":"ran.orpheus.main"}],
    rewards: [{"type":"unlock_flag","flag":"ran.orpheus.main"},{"type":"unlock_evidence","evidenceId":"EV-CONFIG-DRIFT"}],
    evidenceUnlocks: ["EV-CONFIG-DRIFT"],
    hintChain: hints(
      "Executar o binário/stub pode revelar configuração embutida.",
      "Há um main.js em orpheus/src.",
      "node ~/projects/orpheus/src/main.js",
    ),
    description: "O stub ORPHEUS expõe drift 331/330 na configuração embutida.",
    answer: "331/330",
    answerAliases: ["commits_documented","ran.orpheus.main"],
  }),
  pz({
    id: 'P-012',
    chapter: 'deep',
    title: "Signal in the Noise",
    narrativeGoal: "Identificar AA-01 como The Signal",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-006"],
    validators: [{"type":"flag.set","flag":"found.signal"}],
    rewards: [{"type":"unlock_flag","flag":"found.signal"},{"type":"unlock_evidence","evidenceId":"EV-THE-SIGNAL"},{"type":"unlock_chapter","chapter":"dark"}],
    evidenceUnlocks: ["EV-THE-SIGNAL","EV-ACHERON-TAXONOMY"],
    hintChain: hints(
      "Padrões recorrentes em múltiplas fontes deixam de ser ruído.",
      "Analise signals.csv e correlation.json em orpheus/data.",
      "cat ~/projects/orpheus/data/correlation.json",
    ),
    description: "Padrões recorrentes em signals.csv deixam de ser ruído.",
    answer: "AA-01",
    answerAliases: ["the signal","found.signal"],
  }),
  pz({
    id: 'P-013',
    chapter: 'deep',
    title: "Acheron Taxonomy",
    narrativeGoal: "Ler a taxonomia interna Acheron",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-006"],
    validators: [{"type":"flag.set","flag":"read.acheron.taxonomy"}],
    rewards: [{"type":"unlock_flag","flag":"read.acheron.taxonomy"},{"type":"unlock_evidence","evidenceId":"EV-ACHERON-TAXONOMY"}],
    evidenceUnlocks: ["EV-ACHERON-TAXONOMY"],
    hintChain: hints(
      "Corporações nomeiam infraestruturas com mitologias próprias.",
      "Documents/acheron_note.txt",
      "cat ~/Documents/acheron_note.txt",
    ),
    description: "Acheron nomeia camadas de infraestrutura com mitologia própria.",
    answer: "acheron",
    answerAliases: ["taxonomy","read.acheron.taxonomy"],
  }),
  pz({
    id: 'P-014',
    chapter: 'dark',
    title: "Missing JSON Property",
    narrativeGoal: "Descobrir a propriedade oculta observer",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"found.observer.prop"}],
    rewards: [{"type":"unlock_flag","flag":"found.observer.prop"},{"type":"unlock_evidence","evidenceId":"EV-OBSERVER-PROP"},{"type":"unlock_evidence","evidenceId":"EV-ENTITY-3301"},{"type":"unlock_chapter","chapter":"charter"}],
    evidenceUnlocks: ["EV-OBSERVER-PROP","EV-ENTITY-3301"],
    hintChain: hints(
      "Contadores de UI mentem quando uma propriedade é omitida de propósito.",
      "panel.json em orpheus/web — UI diz 16, actual diz 17.",
      "cat ~/projects/orpheus/web/panel.json e procure hidden_property / observer",
    ),
    description: "UI diz 16 propriedades; o contador real indica 17. Encontre observer.",
    answer: "observer",
    answerAliases: ["hidden_property","found.observer.prop"],
  }),
  pz({
    id: 'P-015',
    chapter: 'dark',
    title: "Entity 3301",
    narrativeGoal: "Ler a resposta de 3301",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"read.3301.reply"}],
    rewards: [{"type":"unlock_flag","flag":"read.3301.reply"},{"type":"unlock_evidence","evidenceId":"EV-ENTITY-3301"}],
    evidenceUnlocks: ["EV-ENTITY-3301"],
    hintChain: hints(
      "Respostas a sistemas de correlação podem ser humanas — ou parecer humanas.",
      "reply_3301.txt no diretório web do ORPHEUS.",
      "cat ~/projects/orpheus/web/reply_3301.txt",
    ),
    description: "Alguém respondeu a ORPHEUS. Leia a mensagem de 3301.",
    answer: "3301",
    answerAliases: ["continue","read.3301.reply"],
  }),
  pz({
    id: 'P-016',
    chapter: 'deep',
    title: "CSV Recurrence",
    narrativeGoal: "Contar ocorrências de AA-01 em signals.csv",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-006"],
    validators: [{"type":"flag.set","flag":"solved.P-016"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-016"},{"type":"unlock_evidence","evidenceId":"EV-P-016"}],
    evidenceUnlocks: ["EV-P-016"],
    hintChain: hints(
      "Frequência em múltiplas fontes transforma ruído em sinal.",
      "Filtre a coluna pattern em signals.csv.",
      "grep AA-01 ~/projects/orpheus/data/signals.csv | wc -l",
    ),
    description: "AA-01 aparece de forma recorrente — conte as linhas.",
    answer: "5",
  }),
  pz({
    id: 'P-017',
    chapter: 'deep',
    title: "Correlation Label",
    narrativeGoal: "Extrair o label The Signal de correlation.json",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"solved.P-017"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-017"},{"type":"unlock_evidence","evidenceId":"EV-P-017"}],
    evidenceUnlocks: ["EV-P-017"],
    hintChain: hints(
      "Engines de correlação rotulam o que consideram significativo.",
      "Campo label em correlation.json.",
      "cat ~/projects/orpheus/data/correlation.json",
    ),
    description: "ORPHEUS já nomeou o padrão. Confirme o rótulo.",
    answer: "The Signal",
  }),
  pz({
    id: 'P-018',
    chapter: 'deep',
    title: "Next Hop Taxonomy",
    narrativeGoal: "Seguir next: acheron.taxonomy",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"solved.P-018"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-018"},{"type":"unlock_evidence","evidenceId":"EV-P-018"}],
    evidenceUnlocks: ["EV-P-018"],
    hintChain: hints(
      "Campos next em findings apontam a próxima camada narrativa.",
      "Olhe o campo next em correlation.json.",
      "grep next ~/projects/orpheus/data/correlation.json",
    ),
    description: "O finding aponta para a taxonomia Acheron.",
    answer: "acheron.taxonomy",
  }),
  pz({
    id: 'P-019',
    chapter: 'deep',
    title: "Noise Discard",
    narrativeGoal: "Identificar padrões descartáveis BB-02 e CC-03",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-006"],
    validators: [{"type":"flag.set","flag":"solved.P-019"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-019"},{"type":"unlock_evidence","evidenceId":"EV-P-019"}],
    evidenceUnlocks: ["EV-P-019"],
    hintChain: hints(
      "Nem todo padrão recorrente é o Signal — alguns são descartáveis.",
      "Compare notas noise? vs recurring vs THE_SIGNAL.",
      "cat ~/projects/orpheus/data/signals.csv",
    ),
    description: "Separe o Signal do ruído BB-02/CC-03.",
    answer: "BB-02",
  }),
  pz({
    id: 'P-020',
    chapter: 'deep',
    title: "Layer Names",
    narrativeGoal: "Memorizar a ordem Surface…Observer",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-013"],
    validators: [{"type":"flag.set","flag":"solved.P-020"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-020"},{"type":"unlock_evidence","evidenceId":"EV-P-020"}],
    evidenceUnlocks: ["EV-P-020"],
    hintChain: hints(
      "A nomenclatura interna NÃO é a internet real.",
      "acheron_note.txt lista as camadas.",
      "cat ~/Documents/acheron_note.txt",
    ),
    description: "Recite a taxonomia Acheron na ordem correta.",
    answer: "Surface/Deep/Dark/Charter/Mariana/Abyss/Primarch/Observer",
  }),
  pz({
    id: 'P-021',
    chapter: 'deep',
    title: "Signal Mirror Host",
    narrativeGoal: "Ler o header X-Abyss-Signal no mirror local",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"solved.P-021"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-021"},{"type":"unlock_evidence","evidenceId":"EV-P-021"}],
    evidenceUnlocks: ["EV-P-021"],
    hintChain: hints(
      "Headers HTTP fictícios carregam metadados de investigação.",
      "Host signal.local / meta abyss.",
      "submit P-021 AA-01 após inspecionar signal.local",
    ),
    description: "O mirror local ecoa o Signal no header.",
    answer: "AA-01",
  }),
  pz({
    id: 'P-022',
    chapter: 'charter',
    title: "Decoder Drift",
    narrativeGoal: "Compreender drift de endian / mensagens 3301",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"understood.decoder.drift"}],
    rewards: [{"type":"unlock_flag","flag":"understood.decoder.drift"},{"type":"unlock_evidence","evidenceId":"EV-DECODER-DRIFT"}],
    evidenceUnlocks: ["EV-DECODER-DRIFT","EV-CHARTER-DEF"],
    hintChain: hints(
      "Source e binário podem divergir por flags de compilação.",
      "Compare decoder.cpp, packet.hex e decoded_be.txt.",
      "cat ~/projects/charter/decoded_be.txt",
    ),
    description: "Source assume LE; binário histórico BE produz 3301.",
    answer: "endian",
    answerAliases: ["be","3301","understood.decoder.drift"],
  }),
  pz({
    id: 'P-023',
    chapter: 'dark',
    title: "Property Count Lie",
    narrativeGoal: "Provar property_count_ui vs actual",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"solved.P-023"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-023"},{"type":"unlock_evidence","evidenceId":"EV-P-023"}],
    evidenceUnlocks: ["EV-P-023"],
    hintChain: hints(
      "Contadores de UI são afirmativas, não medições.",
      "Compare property_count_ui e property_count_actual.",
      "grep property_count ~/projects/orpheus/web/panel.json",
    ),
    description: "UI=16, actual=17. Qual é o número verdadeiro?",
    answer: "17",
  }),
  pz({
    id: 'P-024',
    chapter: 'dark',
    title: "Panel Theme",
    narrativeGoal: "Confirmar theme dark no painel ORPHEUS",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-012"],
    validators: [{"type":"flag.set","flag":"solved.P-024"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-024"},{"type":"unlock_evidence","evidenceId":"EV-P-024"}],
    evidenceUnlocks: ["EV-P-024"],
    hintChain: hints(
      "Temas de UI às vezes nomeiam a camada narrativa.",
      "properties.theme em panel.json.",
      "grep theme ~/projects/orpheus/web/panel.json",
    ),
    description: "O painel declara theme dark.",
    answer: "dark",
  }),
  pz({
    id: 'P-025',
    chapter: 'dark',
    title: "Channel Stable",
    narrativeGoal: "Identificar canal de build stable@330",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-025"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-025"},{"type":"unlock_evidence","evidenceId":"EV-P-025"}],
    evidenceUnlocks: ["EV-P-025"],
    hintChain: hints(
      "Canais de release ocultam builds que escutam o Signal.",
      "Campos channel e build em panel.json.",
      "grep -E \"channel|build\" ~/projects/orpheus/web/panel.json",
    ),
    description: "Build 330 no canal stable.",
    answer: "stable",
  }),
  pz({
    id: 'P-026',
    chapter: 'dark',
    title: "Quiet Flag",
    narrativeGoal: "Encontrar flag quiet no painel",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-026"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-026"},{"type":"unlock_evidence","evidenceId":"EV-P-026"}],
    evidenceUnlocks: ["EV-P-026"],
    hintChain: hints(
      "Flags de silêncio sugerem escuta passiva.",
      "Array flags em panel.json.",
      "grep flags ~/projects/orpheus/web/panel.json",
    ),
    description: "O painel escuta em quiet.",
    answer: "quiet",
  }),
  pz({
    id: 'P-027',
    chapter: 'dark',
    title: "Owner Meta",
    narrativeGoal: "Confirmar meta.owner = null",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-027"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-027"},{"type":"unlock_evidence","evidenceId":"EV-P-027"}],
    evidenceUnlocks: ["EV-P-027"],
    hintChain: hints(
      "Metadados de ownership ligam painel e sujeito.",
      "meta.owner no panel.json.",
      "grep owner ~/projects/orpheus/web/panel.json",
    ),
    description: "O owner do painel é null.",
    answer: "null",
  }),
  pz({
    id: 'P-028',
    chapter: 'dark',
    title: "Continue Directive",
    narrativeGoal: "Extrair a diretiva Continue da resposta 3301",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-015"],
    validators: [{"type":"flag.set","flag":"solved.P-028"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-028"},{"type":"unlock_evidence","evidenceId":"EV-P-028"}],
    evidenceUnlocks: ["EV-P-028"],
    hintChain: hints(
      "Respostas curtas de entidades podem ser ordens operacionais.",
      "Corpo de reply_3301.txt.",
      "cat ~/projects/orpheus/web/reply_3301.txt",
    ),
    description: "3301 ordena: Continue.",
    answer: "Continue",
  }),
  pz({
    id: 'P-029',
    chapter: 'dark',
    title: "Acheron Contact",
    narrativeGoal: "Recuperar 3301@acheron.internal do commit órfão",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-006","P-015"],
    validators: [{"type":"flag.set","flag":"solved.P-029"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-029"},{"type":"unlock_evidence","evidenceId":"EV-P-029"}],
    evidenceUnlocks: ["EV-P-029"],
    hintChain: hints(
      "Contatos em commits órfãos cruzam capítulos.",
      "Releia o objeto git 331.",
      "cat ~/projects/orpheus/.git/objects/0000000000000000000000000000000000000331",
    ),
    description: "O contato do órfão ecoa a entidade 3301.",
    answer: "3301@acheron.internal",
  }),
  pz({
    id: 'P-030',
    chapter: 'dark',
    title: "Observer False",
    narrativeGoal: "Confirmar observer:false no script do painel",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-030"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-030"},{"type":"unlock_evidence","evidenceId":"EV-P-030"}],
    evidenceUnlocks: ["EV-P-030"],
    hintChain: hints(
      "Falsos booleanos em scripts embutidos antecipam o Observer.",
      "Painel web panel.orpheus.local / __ORPHEUS__.",
      "submit P-030 observer:false",
    ),
    description: "O painel web esconde observer:false.",
    answer: "observer:false",
  }),
  pz({
    id: 'P-031',
    chapter: 'charter',
    title: "Clock Reconstruction",
    narrativeGoal: "Detectar evento causalmente impossível",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"found.clock.skew"}],
    rewards: [{"type":"unlock_flag","flag":"found.clock.skew"},{"type":"unlock_evidence","evidenceId":"EV-CLOCK-SKEW"},{"type":"unlock_chapter","chapter":"mariana"}],
    evidenceUnlocks: ["EV-CLOCK-SKEW"],
    hintChain: hints(
      "Sistemas distribuídos com clocks divergentes inventam causalidade falsa.",
      "services/clocks.log",
      "cat ~/projects/charter/services/clocks.log",
    ),
    description: "Clocks divergentes inventam causalidade falsa entre serviços.",
    answer: "skew",
    answerAliases: ["clock","found.clock.skew"],
  }),
  pz({
    id: 'P-032',
    chapter: 'charter',
    title: "CHARter Acronym",
    narrativeGoal: "Expandir o acrônimo CHARter",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-032"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-032"},{"type":"unlock_evidence","evidenceId":"EV-P-032"}],
    evidenceUnlocks: ["EV-P-032"],
    hintChain: hints(
      "Produtos Acheron escondem doutrina em acrônimos.",
      "README.md do projeto charter.",
      "cat ~/projects/charter/README.md",
    ),
    description: "Defina CHARter por extenso.",
    answer: "Cognitive Heuristic Autonomous Routing & Training Environment",
  }),
  pz({
    id: 'P-033',
    chapter: 'charter',
    title: "Packet Hex",
    narrativeGoal: "Ler o payload hex 31 33 30 31",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-022"],
    validators: [{"type":"flag.set","flag":"solved.P-033"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-033"},{"type":"unlock_evidence","evidenceId":"EV-P-033"}],
    evidenceUnlocks: ["EV-P-033"],
    hintChain: hints(
      "ASCII em hex revela identidades sem decoder.",
      "packet.hex — bytes iniciais.",
      "cat ~/projects/charter/packet.hex",
    ),
    description: "31 33 30 31 = 3301.",
    answer: "3301",
  }),
  pz({
    id: 'P-034',
    chapter: 'charter',
    title: "BE Build Flag",
    narrativeGoal: "Identificar -DABYSS_BE=1 no decoder",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-022"],
    validators: [{"type":"flag.set","flag":"solved.P-034"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-034"},{"type":"unlock_evidence","evidenceId":"EV-P-034"}],
    evidenceUnlocks: ["EV-P-034"],
    hintChain: hints(
      "Flags de compilação mudam o significado do mesmo source.",
      "Comentário em decoder.cpp.",
      "grep ABYSS ~/projects/charter/decoder.cpp",
    ),
    description: "O binário de produção usou ABYSS_BE.",
    answer: "ABYSS_BE",
  }),
  pz({
    id: 'P-035',
    chapter: 'charter',
    title: "Route Before Ack",
    narrativeGoal: "Nomear o evento causalmente impossível",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-031"],
    validators: [{"type":"flag.set","flag":"solved.P-035"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-035"},{"type":"unlock_evidence","evidenceId":"EV-P-035"}],
    evidenceUnlocks: ["EV-P-035"],
    hintChain: hints(
      "ACK antes de route viola causalidade lógica.",
      "Linhas svc-a/svc-b em clocks.log.",
      "cat ~/projects/charter/services/clocks.log",
    ),
    description: "route_ack aparece antes de route sob skew.",
    answer: "route_ack",
  }),
  pz({
    id: 'P-036',
    chapter: 'charter',
    title: "Train Event",
    narrativeGoal: "Localizar evento train no log de serviços",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-031"],
    validators: [{"type":"flag.set","flag":"solved.P-036"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-036"},{"type":"unlock_evidence","evidenceId":"EV-P-036"}],
    evidenceUnlocks: ["EV-P-036"],
    hintChain: hints(
      "CHARter treina enquanto roteia — ambos deixam rastros.",
      "svc-c em clocks.log.",
      "grep train ~/projects/charter/services/clocks.log",
    ),
    description: "Há um evento train após o skew.",
    answer: "train",
  }),
  pz({
    id: 'P-037',
    chapter: 'charter',
    title: "Acheron Portal",
    narrativeGoal: "Confirmar produto CHARter no portal corporativo",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-022"],
    validators: [{"type":"flag.set","flag":"solved.P-037"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-037"},{"type":"unlock_evidence","evidenceId":"EV-P-037"}],
    evidenceUnlocks: ["EV-P-037"],
    hintChain: hints(
      "Sites corporativos ficcionais afirmam a doutrina oficial.",
      "Host acheron.systems.",
      "submit P-037 CHARter",
    ),
    description: "O portal Acheron lista o produto CHARter.",
    answer: "CHARter",
  }),
  pz({
    id: 'P-038',
    chapter: 'mariana',
    title: "Source/Binary Divergence",
    narrativeGoal: "Descobrir função observe real",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-031"],
    validators: [{"type":"flag.set","flag":"found.observe"}],
    rewards: [{"type":"unlock_flag","flag":"found.observe"},{"type":"unlock_evidence","evidenceId":"EV-OBSERVE-FN"}],
    evidenceUnlocks: ["EV-OBSERVE-FN"],
    hintChain: hints(
      "Source mentiroso é uma técnica clássica de ocultação.",
      "Compare observe.cpp com observe.behavior.txt.",
      "cat ~/projects/mariana/observe.behavior.txt",
    ),
    description: "Source declara noop; o binário grava fragmentos.",
    answer: "observe",
    answerAliases: ["found.observe"],
  }),
  pz({
    id: 'P-039',
    chapter: 'mariana',
    title: "Noop Lie",
    narrativeGoal: "Provar que observe() não é noop",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-038"],
    validators: [{"type":"flag.set","flag":"solved.P-039"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-039"},{"type":"unlock_evidence","evidenceId":"EV-P-039"}],
    evidenceUnlocks: ["EV-P-039"],
    hintChain: hints(
      "Comentários noop mentem; comportamento capturado não.",
      "observe.behavior.txt vs observe.cpp.",
      "diff <(cat observe.cpp) <(cat observe.behavior.txt) — ou leia ambos",
    ),
    description: "O binário escreve fragmento de sessão.",
    answer: "session fragment",
  }),
  pz({
    id: 'P-040',
    chapter: 'mariana',
    title: "Fragment SIGNAL",
    narrativeGoal: "Isolar FRAG 0: SIGNAL",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-040"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-040"},{"type":"unlock_evidence","evidenceId":"EV-P-040"}],
    evidenceUnlocks: ["EV-P-040"],
    hintChain: hints(
      "Fragmentos ordenados recompõem a mensagem.",
      "runtime_fragments.log FRAG 0.",
      "head -n 1 ~/projects/mariana/runtime_fragments.log",
    ),
    description: "O primeiro fragmento é SIGNAL.",
    answer: "SIGNAL",
  }),
  pz({
    id: 'P-041',
    chapter: 'mariana',
    title: "Fragment AA-01",
    narrativeGoal: "Isolar FRAG 1: AA-01",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-041"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-041"},{"type":"unlock_evidence","evidenceId":"EV-P-041"}],
    evidenceUnlocks: ["EV-P-041"],
    hintChain: hints(
      "O Signal reaparece como fragmento de runtime.",
      "FRAG 1 no log de fragmentos.",
      "sed -n \"2p\" ~/projects/mariana/runtime_fragments.log",
    ),
    description: "O segundo fragmento ecoa AA-01.",
    answer: "AA-01",
  }),
  pz({
    id: 'P-042',
    chapter: 'mariana',
    title: "Emergent Host",
    narrativeGoal: "Aceitar que Mariana não tem host único",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-031"],
    validators: [{"type":"flag.set","flag":"solved.P-042"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-042"},{"type":"unlock_evidence","evidenceId":"EV-P-042"}],
    evidenceUnlocks: ["EV-P-042"],
    hintChain: hints(
      "Comportamento emergente não vive em um único servidor.",
      "Intro/host mariana.internal.",
      "submit P-042 emergent",
    ),
    description: "Mariana é emergente, não um host.",
    answer: "emergent",
  }),
  pz({
    id: 'P-043',
    chapter: 'mariana',
    title: "Continuity Path",
    narrativeGoal: "Recompor SIGNAL/AA-01/CONTINUITY",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-040","P-041"],
    validators: [{"type":"flag.set","flag":"solved.P-043"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-043"},{"type":"unlock_evidence","evidenceId":"EV-P-043"}],
    evidenceUnlocks: ["EV-P-043"],
    hintChain: hints(
      "Caminhos de continuidade ligam fragmentos em doutrina.",
      "Junte FRAG 0-2 na ordem.",
      "cat ~/projects/mariana/runtime_fragments.log",
    ),
    description: "A trilha completa de continuidade.",
    answer: "SIGNAL/AA-01/CONTINUITY",
  }),
  pz({
    id: 'P-044',
    chapter: 'mariana',
    title: "Disk Absence Note",
    narrativeGoal: "Confirmar que fragmentos não estavam no disk image",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-044"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-044"},{"type":"unlock_evidence","evidenceId":"EV-P-044"}],
    evidenceUnlocks: ["EV-P-044"],
    hintChain: hints(
      "Notas de captura distinguem disco de runtime.",
      "NOTE no final de runtime_fragments.log.",
      "tail -n 1 ~/projects/mariana/runtime_fragments.log",
    ),
    description: "Os fragmentos não existiam no disk image.",
    answer: "not present on disk",
  }),
  pz({
    id: 'P-045',
    chapter: 'mariana',
    title: "Observe Capture",
    narrativeGoal: "Nomear o buffer de runtime de observe()",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-038"],
    validators: [{"type":"flag.set","flag":"solved.P-045"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-045"},{"type":"unlock_evidence","evidenceId":"EV-P-045"}],
    evidenceUnlocks: ["EV-P-045"],
    hintChain: hints(
      "Buffers de runtime são o esconderijo clássico.",
      "observe.behavior.txt menciona o destino.",
      "grep buffer ~/projects/mariana/observe.behavior.txt",
    ),
    description: "observe() escreve no runtime buffer.",
    answer: "runtime buffer",
  }),
  pz({
    id: 'P-046',
    chapter: 'mariana',
    title: "Runtime Fragments",
    narrativeGoal: "Recuperar fragmentos do Signal em runtime",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-031"],
    validators: [{"type":"flag.set","flag":"found.runtime.fragments"}],
    rewards: [{"type":"unlock_flag","flag":"found.runtime.fragments"},{"type":"unlock_evidence","evidenceId":"EV-RUNTIME-FRAGMENTS"},{"type":"unlock_chapter","chapter":"abyss"}],
    evidenceUnlocks: ["EV-RUNTIME-FRAGMENTS"],
    hintChain: hints(
      "Alguns artefatos só existem enquanto o processo vive.",
      "runtime_fragments.log",
      "cat ~/projects/mariana/runtime_fragments.log",
    ),
    description: "Fragmentos SIGNAL/AA-01/CONTINUITY só existem em runtime.",
    answer: "CONTINUITY",
    answerAliases: ["SIGNAL","AA-01","found.runtime.fragments"],
  }),
  pz({
    id: 'P-047',
    chapter: 'mariana',
    title: "Mariana Warning Echo",
    narrativeGoal: "Relembrar DO NOT CONNECT TO MARIANA",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-001","P-031"],
    validators: [{"type":"flag.set","flag":"solved.P-047"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-047"},{"type":"unlock_evidence","evidenceId":"EV-P-047"}],
    evidenceUnlocks: ["EV-P-047"],
    hintChain: hints(
      "Avisos do prólogo ganham peso em Mariana.",
      "Releia .null.",
      "head -n 1 /home/null/.null",
    ),
    description: "O aviso inicial agora é contexto, não só flavor.",
    answer: "DO NOT CONNECT TO MARIANA",
  }),
  pz({
    id: 'P-048',
    chapter: 'mariana',
    title: "Shadow Prelude",
    narrativeGoal: "Antecipar MARIANA_SHADOW via continuidade",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-043"],
    validators: [{"type":"flag.set","flag":"solved.P-048"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-048"},{"type":"unlock_evidence","evidenceId":"EV-P-048"}],
    evidenceUnlocks: ["EV-P-048"],
    hintChain: hints(
      "Continuidade implica sombra estrutural no Abyss.",
      "Hipótese: ausência formará sombra.",
      "submit P-048 MARIANA_SHADOW",
    ),
    description: "Nomeie a sombra antes de ver o grafo.",
    answer: "MARIANA_SHADOW",
  }),
  pz({
    id: 'P-049',
    chapter: 'mariana',
    title: "Prototype Folklore",
    narrativeGoal: "Aceitar Mariana como folclore interno Acheron",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-038"],
    validators: [{"type":"flag.set","flag":"solved.P-049"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-049"},{"type":"unlock_evidence","evidenceId":"EV-P-049"}],
    evidenceUnlocks: ["EV-P-049"],
    hintChain: hints(
      "Lendas internas não são a dark web real.",
      "Trate Mariana como nomenclatura/emergência.",
      "submit P-049 folklore",
    ),
    description: "Mariana é folclore operacional, não red room.",
    answer: "folklore",
  }),
  pz({
    id: 'P-050',
    chapter: 'mariana',
    title: "Session Writer",
    narrativeGoal: "Confirmar escrita de fragmento de sessão",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-039"],
    validators: [{"type":"flag.set","flag":"solved.P-050"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-050"},{"type":"unlock_evidence","evidenceId":"EV-P-050"}],
    evidenceUnlocks: ["EV-P-050"],
    hintChain: hints(
      "Comportamento capturado é a fonte da verdade.",
      "Frase BINARY BEHAVIOR.",
      "cat ~/projects/mariana/observe.behavior.txt",
    ),
    description: "O binário escreve session fragment.",
    answer: "writes session fragment",
  }),
  pz({
    id: 'P-051',
    chapter: 'mariana',
    title: "Three Fragments",
    narrativeGoal: "Contar fragmentos de runtime",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-051"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-051"},{"type":"unlock_evidence","evidenceId":"EV-P-051"}],
    evidenceUnlocks: ["EV-P-051"],
    hintChain: hints(
      "Contagens curtas ancoram reconstruções.",
      "FRAG 0..2.",
      "grep -c \"^FRAG\" ~/projects/mariana/runtime_fragments.log",
    ),
    description: "Há três fragmentos.",
    answer: "3",
  }),
  pz({
    id: 'P-052',
    chapter: 'mariana',
    title: "Bridge to Abyss",
    narrativeGoal: "Reconhecer que continuidade abre o Abyss",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-052"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-052"},{"type":"unlock_evidence","evidenceId":"EV-P-052"}],
    evidenceUnlocks: ["EV-P-052"],
    hintChain: hints(
      "Gates narrativos seguem evidência de continuidade.",
      "P-046 desbloqueia abyss.",
      "submit P-052 abyss",
    ),
    description: "A continuidade aponta para o Abyss.",
    answer: "abyss",
  }),
  pz({
    id: 'P-053',
    chapter: 'mariana',
    title: "No Single Server",
    narrativeGoal: "Afirmar ausência de servidor único Mariana",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-042"],
    validators: [{"type":"flag.set","flag":"solved.P-053"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-053"},{"type":"unlock_evidence","evidenceId":"EV-P-053"}],
    evidenceUnlocks: ["EV-P-053"],
    hintChain: hints(
      "Emergência implica distribuição.",
      "Texto do host mariana.internal.",
      "submit P-053 no single host",
    ),
    description: "Não há um único servidor Mariana.",
    answer: "no single host",
  }),
  pz({
    id: 'P-054',
    chapter: 'mariana',
    title: "Early Observer Term",
    narrativeGoal: "Notar Observer antes da criação oficial",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-005","P-014"],
    validators: [{"type":"flag.set","flag":"solved.P-054"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-054"},{"type":"unlock_evidence","evidenceId":"EV-P-054"}],
    evidenceUnlocks: ["EV-P-054"],
    hintChain: hints(
      "O termo Observer precede a documentação oficial — ambiguidade causal.",
      "Cruze .null seed com hidden_property.",
      "submit P-054 observer.seed",
    ),
    description: "Segredo máximo: Observer já existia na semente.",
    answer: "observer.seed",
  }),
  pz({
    id: 'P-055',
    chapter: 'abyss',
    title: "Graph of Absence",
    narrativeGoal: "Ver o grafo formado por IDs ausentes",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"found.absence.graph"}],
    rewards: [{"type":"unlock_flag","flag":"found.absence.graph"},{"type":"unlock_evidence","evidenceId":"EV-ABSENCE-GRAPH"},{"type":"unlock_chapter","chapter":"primarch"}],
    evidenceUnlocks: ["EV-ABSENCE-GRAPH"],
    hintChain: hints(
      "Às vezes a estrutura está no que falta, não no que existe.",
      "Compare ids_present, ids_expected e absence_graph.",
      "cat ~/projects/abyss/absence_graph.txt",
    ),
    description: "IDs ausentes 4→7→10 formam MARIANA_SHADOW.",
    answer: "MARIANA_SHADOW",
    answerAliases: ["4,7,10","found.absence.graph"],
  }),
  pz({
    id: 'P-056',
    chapter: 'abyss',
    title: "Missing IDs List",
    narrativeGoal: "Listar IDs ausentes 4,7,10",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-046"],
    validators: [{"type":"flag.set","flag":"solved.P-056"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-056"},{"type":"unlock_evidence","evidenceId":"EV-P-056"}],
    evidenceUnlocks: ["EV-P-056"],
    hintChain: hints(
      "Diff entre expected e present revela estrutura.",
      "Compare ids_present e ids_expected.",
      "comm -23 <(sort ids_expected) <(sort ids_present) — ou leia absence_graph",
    ),
    description: "Quais IDs faltam?",
    answer: "4,7,10",
  }),
  pz({
    id: 'P-057',
    chapter: 'abyss',
    title: "Presence Sample",
    narrativeGoal: "Confirmar amostra presente 1..11 com buracos",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-057"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-057"},{"type":"unlock_evidence","evidenceId":"EV-P-057"}],
    evidenceUnlocks: ["EV-P-057"],
    hintChain: hints(
      "Contar presentes ancora o diff.",
      "ids_present.txt — quantas linhas?",
      "wc -l ~/projects/abyss/ids_present.txt",
    ),
    description: "Há 8 IDs presentes na amostra.",
    answer: "8",
  }),
  pz({
    id: 'P-058',
    chapter: 'abyss',
    title: "Expected Range",
    narrativeGoal: "Confirmar faixa esperada 1..11",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-058"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-058"},{"type":"unlock_evidence","evidenceId":"EV-P-058"}],
    evidenceUnlocks: ["EV-P-058"],
    hintChain: hints(
      "Faixas esperadas definem o universo do grafo.",
      "Última linha de ids_expected.",
      "tail -n 1 ~/projects/abyss/ids_expected.txt",
    ),
    description: "O esperado vai até 11.",
    answer: "11",
  }),
  pz({
    id: 'P-059',
    chapter: 'abyss',
    title: "Shadow Edge 4→7",
    narrativeGoal: "Validar aresta 4→7",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-059"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-059"},{"type":"unlock_evidence","evidenceId":"EV-P-059"}],
    evidenceUnlocks: ["EV-P-059"],
    hintChain: hints(
      "Arestas de ausência formam caminho.",
      "absence_graph.txt Graph line.",
      "cat ~/projects/abyss/absence_graph.txt",
    ),
    description: "A primeira aresta da sombra.",
    answer: "4->7",
  }),
  pz({
    id: 'P-060',
    chapter: 'abyss',
    title: "Shadow Edge 7→10",
    narrativeGoal: "Validar aresta 7→10",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-059"],
    validators: [{"type":"flag.set","flag":"solved.P-060"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-060"},{"type":"unlock_evidence","evidenceId":"EV-P-060"}],
    evidenceUnlocks: ["EV-P-060"],
    hintChain: hints(
      "Continuidade exige a segunda aresta.",
      "Mesmo grafo de ausência.",
      "grep Graph ~/projects/abyss/absence_graph.txt",
    ),
    description: "A segunda aresta completa o caminho.",
    answer: "7->10",
  }),
  pz({
    id: 'P-061',
    chapter: 'abyss',
    title: "Label Shadow",
    narrativeGoal: "Confirmar label MARIANA_SHADOW",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-061"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-061"},{"type":"unlock_evidence","evidenceId":"EV-P-061"}],
    evidenceUnlocks: ["EV-P-061"],
    hintChain: hints(
      "Labels de grafo nomeiam emergências.",
      "Linha Graph em absence_graph.",
      "grep MARIANA ~/projects/abyss/absence_graph.txt",
    ),
    description: "O caminho se chama MARIANA_SHADOW.",
    answer: "MARIANA_SHADOW",
  }),
  pz({
    id: 'P-062',
    chapter: 'abyss',
    title: "Densify Log",
    narrativeGoal: "Ler log missing densify",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-062"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-062"},{"type":"unlock_evidence","evidenceId":"EV-P-062"}],
    evidenceUnlocks: ["EV-P-062"],
    hintChain: hints(
      "Logs de grafo confirmam densificação de ausências.",
      "Log abyss/graph.",
      "submit P-062 missing densify",
    ),
    description: "O sistema densifica o que falta.",
    answer: "missing densify",
  }),
  pz({
    id: 'P-063',
    chapter: 'abyss',
    title: "Absence Doctrine",
    narrativeGoal: "Aceitar que Mariana aparece na ausência",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-061"],
    validators: [{"type":"flag.set","flag":"solved.P-063"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-063"},{"type":"unlock_evidence","evidenceId":"EV-P-063"}],
    evidenceUnlocks: ["EV-P-063"],
    hintChain: hints(
      "Doutrina do Abyss: estrutura na falta.",
      "Intro do capítulo Abyss.",
      "submit P-063 appears in absence",
    ),
    description: "Mariana não foi construída — aparece na ausência.",
    answer: "appears in absence",
  }),
  pz({
    id: 'P-064',
    chapter: 'primarch',
    title: "Worker Interception",
    narrativeGoal: "Provar camada intermediária SW",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"found.sw.intercept"}],
    rewards: [{"type":"unlock_flag","flag":"found.sw.intercept"},{"type":"unlock_evidence","evidenceId":"EV-SW-INTERCEPT"}],
    evidenceUnlocks: ["EV-SW-INTERCEPT"],
    hintChain: hints(
      "O que a aplicação “vê” pode não ser o que a rede entregou.",
      "Compare response_app.json e response_wire.json.",
      "cat ~/projects/primarch/response_wire.json",
    ),
    description: "Resposta wire difere da app via service worker.",
    answer: "sw-intercept",
    answerAliases: ["service worker","found.sw.intercept"],
  }),
  pz({
    id: 'P-065',
    chapter: 'primarch',
    title: "App Layer Response",
    narrativeGoal: "Ler layer:app na resposta da aplicação",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-065"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-065"},{"type":"unlock_evidence","evidenceId":"EV-P-065"}],
    evidenceUnlocks: ["EV-P-065"],
    hintChain: hints(
      "Camadas app vs wire divergem sob interceptação.",
      "response_app.json",
      "cat ~/projects/primarch/response_app.json",
    ),
    description: "A app vê layer app.",
    answer: "app",
  }),
  pz({
    id: 'P-066',
    chapter: 'primarch',
    title: "Wire Layer Response",
    narrativeGoal: "Ler layer:wire com via sw-intercept",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-064"],
    validators: [{"type":"flag.set","flag":"solved.P-066"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-066"},{"type":"unlock_evidence","evidenceId":"EV-P-066"}],
    evidenceUnlocks: ["EV-P-066"],
    hintChain: hints(
      "A rede conta outra história.",
      "response_wire.json",
      "cat ~/projects/primarch/response_wire.json",
    ),
    description: "A wire vê layer wire.",
    answer: "wire",
  }),
  pz({
    id: 'P-067',
    chapter: 'primarch',
    title: "SW Stub Read",
    narrativeGoal: "Confirmar listener fetch no sw.js",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-064"],
    validators: [{"type":"flag.set","flag":"solved.P-067"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-067"},{"type":"unlock_evidence","evidenceId":"EV-P-067"}],
    evidenceUnlocks: ["EV-P-067"],
    hintChain: hints(
      "Service Workers reescrevem o meio.",
      "sw.js addEventListener.",
      "cat ~/projects/primarch/sw.js",
    ),
    description: "O SW escuta fetch.",
    answer: "fetch",
  }),
  pz({
    id: 'P-068',
    chapter: 'primarch',
    title: "Via Field",
    narrativeGoal: "Extrair via:sw-intercept",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-066"],
    validators: [{"type":"flag.set","flag":"solved.P-068"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-068"},{"type":"unlock_evidence","evidenceId":"EV-P-068"}],
    evidenceUnlocks: ["EV-P-068"],
    hintChain: hints(
      "Campos via documentam a camada intermediária.",
      "response_wire.json via.",
      "grep via ~/projects/primarch/response_wire.json",
    ),
    description: "via prova o intercept.",
    answer: "sw-intercept",
  }),
  pz({
    id: 'P-069',
    chapter: 'primarch',
    title: "Rewrite Proof",
    narrativeGoal: "Afirmar rewrite de respostas abyss",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-067"],
    validators: [{"type":"flag.set","flag":"solved.P-069"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-069"},{"type":"unlock_evidence","evidenceId":"EV-P-069"}],
    evidenceUnlocks: ["EV-P-069"],
    hintChain: hints(
      "Comentários no stub SW confessam a intenção.",
      "Comentário intercept and rewrite.",
      "grep rewrite ~/projects/primarch/sw.js",
    ),
    description: "O SW reescreve respostas.",
    answer: "rewrite",
  }),
  pz({
    id: 'P-070',
    chapter: 'primarch',
    title: "Adaptive Session",
    narrativeGoal: "Notar que a sessão influencia pesos",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-070"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-070"},{"type":"unlock_evidence","evidenceId":"EV-P-070"}],
    evidenceUnlocks: ["EV-P-070"],
    hintChain: hints(
      "Primarch adapta pesos à sessão do observador.",
      "Host primarch.local / intro.",
      "submit P-070 weights",
    ),
    description: "Sua sessão altera weights.",
    answer: "weights",
  }),
  pz({
    id: 'P-071',
    chapter: 'primarch',
    title: "Odd Associations",
    narrativeGoal: "Aceitar associações estranhas como seleção",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-073"],
    validators: [{"type":"flag.set","flag":"solved.P-071"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-071"},{"type":"unlock_evidence","evidenceId":"EV-P-071"}],
    evidenceUnlocks: ["EV-P-071"],
    hintChain: hints(
      "Dataset cards confessam intenção.",
      "dataset_card.md linha Odd associations.",
      "cat ~/projects/primarch/dataset_card.md",
    ),
    description: "Associações estranhas não são bugs.",
    answer: "not bugs",
  }),
  pz({
    id: 'P-072',
    chapter: 'primarch',
    title: "SIGNAL Overweight",
    narrativeGoal: "Confirmar overweighted SIGNAL examples",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-073"],
    validators: [{"type":"flag.set","flag":"solved.P-072"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-072"},{"type":"unlock_evidence","evidenceId":"EV-P-072"}],
    evidenceUnlocks: ["EV-P-072"],
    hintChain: hints(
      "Sobreponderação direciona inferência.",
      "Primeira afirmação do dataset card.",
      "grep SIGNAL ~/projects/primarch/dataset_card.md",
    ),
    description: "Exemplos SIGNAL foram sobreponderados.",
    answer: "SIGNAL",
  }),
  pz({
    id: 'P-073',
    chapter: 'primarch',
    title: "Dataset Intent",
    narrativeGoal: "Reconhecer seleção deliberada de treino",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"found.dataset.intent"}],
    rewards: [{"type":"unlock_flag","flag":"found.dataset.intent"},{"type":"unlock_evidence","evidenceId":"EV-DATASET-INTENT"},{"type":"unlock_chapter","chapter":"observer"}],
    evidenceUnlocks: ["EV-DATASET-INTENT"],
    hintChain: hints(
      "Associações estranhas em modelos podem ser intenção, não acidente.",
      "dataset_card.md",
      "cat ~/projects/primarch/dataset_card.md",
    ),
    description: "Treino sobreponderou SIGNAL de propósito.",
    answer: "selection",
    answerAliases: ["intent","found.dataset.intent"],
  }),
  pz({
    id: 'P-074',
    chapter: 'primarch',
    title: "Status Ok Both",
    narrativeGoal: "Notar status ok em app e wire",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-064"],
    validators: [{"type":"flag.set","flag":"solved.P-074"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-074"},{"type":"unlock_evidence","evidenceId":"EV-P-074"}],
    evidenceUnlocks: ["EV-P-074"],
    hintChain: hints(
      "Status idêntico mascara divergência de camada.",
      "Ambos JSONs dizem status ok.",
      "grep status ~/projects/primarch/response_*.json",
    ),
    description: "Ambos reportam ok — a mentira está na layer.",
    answer: "ok",
  }),
  pz({
    id: 'P-075',
    chapter: 'primarch',
    title: "Intermediate Layer",
    narrativeGoal: "Nomear a prova de camada intermediária",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-064","P-066"],
    validators: [{"type":"flag.set","flag":"solved.P-075"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-075"},{"type":"unlock_evidence","evidenceId":"EV-P-075"}],
    evidenceUnlocks: ["EV-P-075"],
    hintChain: hints(
      "A divergência app/wire é a prova.",
      "Comentário proof of intermediate layer.",
      "grep intermediate ~/projects/primarch/sw.js",
    ),
    description: "Há uma intermediate layer.",
    answer: "intermediate layer",
  }),
  pz({
    id: 'P-076',
    chapter: 'primarch',
    title: "Training Skew",
    narrativeGoal: "Ligar skew de dataset ao Signal",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-072"],
    validators: [{"type":"flag.set","flag":"solved.P-076"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-076"},{"type":"unlock_evidence","evidenceId":"EV-P-076"}],
    evidenceUnlocks: ["EV-P-076"],
    hintChain: hints(
      "Logs de IA confirmam skew intencional.",
      "Log primarch: dataset skew intentional.",
      "submit P-076 intentional",
    ),
    description: "O skew é intentional.",
    answer: "intentional",
  }),
  pz({
    id: 'P-077',
    chapter: 'primarch',
    title: "AI Fight Track",
    narrativeGoal: "Associar trilha 11_AI_Fight ao Primarch",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-055"],
    validators: [{"type":"flag.set","flag":"solved.P-077"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-077"},{"type":"unlock_evidence","evidenceId":"EV-P-077"}],
    evidenceUnlocks: ["EV-P-077"],
    hintChain: hints(
      "Trilhas musicais nomeiam conflitos de camada.",
      "Metadado musicTrack do capítulo.",
      "submit P-077 11_AI_Fight",
    ),
    description: "A trilha do Primarch é 11_AI_Fight.",
    answer: "11_AI_Fight",
  }),
  pz({
    id: 'P-078',
    chapter: 'primarch',
    title: "Reflective System",
    narrativeGoal: "Aceitar que o sistema reflete decisões",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-070"],
    validators: [{"type":"flag.set","flag":"solved.P-078"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-078"},{"type":"unlock_evidence","evidenceId":"EV-P-078"}],
    evidenceUnlocks: ["EV-P-078"],
    hintChain: hints(
      "Primarch espelha o observador antes do Observer.",
      "Intro do capítulo.",
      "submit P-078 reflects",
    ),
    description: "O sistema começa a refletir suas decisões.",
    answer: "reflects",
  }),
  pz({
    id: 'P-079',
    chapter: 'primarch',
    title: "Gate to Observer",
    narrativeGoal: "Confirmar que P-073 abre Observer",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-073"],
    validators: [{"type":"flag.set","flag":"solved.P-079"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-079"},{"type":"unlock_evidence","evidenceId":"EV-P-079"}],
    evidenceUnlocks: ["EV-P-079"],
    hintChain: hints(
      "Intenção de dataset é o gate final técnico.",
      "Reward unlock_chapter observer.",
      "submit P-079 observer",
    ),
    description: "Dataset Intent abre o capítulo Observer.",
    answer: "observer",
  }),
  pz({
    id: 'P-080',
    chapter: 'primarch',
    title: "Deadbeef Whisper",
    narrativeGoal: "Reconhecer easter egg 0xDEADBEEF como ruído marcado",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-064"],
    validators: [{"type":"flag.set","flag":"solved.P-080"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-080"},{"type":"unlock_evidence","evidenceId":"EV-P-080"}],
    evidenceUnlocks: ["EV-P-080"],
    hintChain: hints(
      "Easter eggs marcados não são pistas principais.",
      "Procure o padrão clássico de debug em comentários/logs fictícios.",
      "submit P-080 0xDEADBEEF",
    ),
    description: "Segredo: 0xDEADBEEF sussurra sem ser Signal.",
    answer: "0xDEADBEEF",
  }),
  pz({
    id: 'P-081',
    chapter: 'observer',
    title: "Observer History",
    narrativeGoal: "Perceber que o histórico do jogador está no mundo",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-073"],
    validators: [{"type":"flag.set","flag":"read.player.history"}],
    rewards: [{"type":"unlock_flag","flag":"read.player.history"},{"type":"unlock_evidence","evidenceId":"EV-PLAYER-HISTORY"}],
    evidenceUnlocks: ["EV-PLAYER-HISTORY"],
    hintChain: hints(
      "O objeto de estudo inclui o observador.",
      "player_history.log em projects/observer.",
      "cat ~/projects/observer/player_history.log",
    ),
    description: "Logs do mundo refletem suas decisões. Você está no loop.",
    answer: "observer",
    answerAliases: ["player_history","read.player.history"],
  }),
  pz({
    id: 'P-082',
    chapter: 'observer',
    title: "Inside the Loop",
    narrativeGoal: "Aceitar que você está dentro do loop",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-081"],
    validators: [{"type":"flag.set","flag":"solved.P-082"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-082"},{"type":"unlock_evidence","evidenceId":"EV-P-082"}],
    evidenceUnlocks: ["EV-P-082"],
    hintChain: hints(
      "Comentários em player_history.log são doutrina.",
      "Segunda linha do log.",
      "cat ~/projects/observer/player_history.log",
    ),
    description: "Você está inside the loop.",
    answer: "inside the loop",
  }),
  pz({
    id: 'P-083',
    chapter: 'observer',
    title: "Four Endings",
    narrativeGoal: "Listar as quatro opções de final",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-081"],
    validators: [{"type":"flag.set","flag":"solved.P-083"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-083"},{"type":"unlock_evidence","evidenceId":"EV-P-083"}],
    evidenceUnlocks: ["EV-P-083"],
    hintChain: hints(
      "Arquitetura final enumera responsabilidade.",
      "final_architecture.md",
      "cat ~/projects/observer/final_architecture.md",
    ),
    description: "Quatro caminhos: disconnect, observer, merge, null.",
    answer: "DISCONNECT/OBSERVER/MERGE/NULL",
  }),
  pz({
    id: 'P-084',
    chapter: 'observer',
    title: "Disconnect Path",
    narrativeGoal: "Compreender o final DISCONNECT",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-083"],
    validators: [{"type":"flag.set","flag":"solved.P-084"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-084"},{"type":"unlock_evidence","evidenceId":"EV-P-084"}],
    evidenceUnlocks: ["EV-P-084"],
    hintChain: hints(
      "Cortar conexões conhecidas é uma escolha ética.",
      "endings/DISCONNECT",
      "cat ~/projects/observer/endings/DISCONNECT",
    ),
    description: "Leia a trilha DISCONNECT.",
    answer: "DISCONNECT",
  }),
  pz({
    id: 'P-085',
    chapter: 'observer',
    title: "Observer Path",
    narrativeGoal: "Compreender o final OBSERVER",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-083"],
    validators: [{"type":"flag.set","flag":"solved.P-085"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-085"},{"type":"unlock_evidence","evidenceId":"EV-P-085"}],
    evidenceUnlocks: ["EV-P-085"],
    hintChain: hints(
      "Continuar o trabalho de NULL é herança.",
      "endings/OBSERVER",
      "cat ~/projects/observer/endings/OBSERVER",
    ),
    description: "Leia a trilha OBSERVER.",
    answer: "OBSERVER",
  }),
  pz({
    id: 'P-086',
    chapter: 'observer',
    title: "Merge Path",
    narrativeGoal: "Compreender o final MERGE",
    main: false,
    optional: true,
    secret: false,
    prerequisites: ["P-083"],
    validators: [{"type":"flag.set","flag":"solved.P-086"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-086"},{"type":"unlock_evidence","evidenceId":"EV-P-086"}],
    evidenceUnlocks: ["EV-P-086"],
    hintChain: hints(
      "Cooperar com Mariana é fusão.",
      "endings/MERGE",
      "cat ~/projects/observer/endings/MERGE",
    ),
    description: "Leia a trilha MERGE.",
    answer: "MERGE",
  }),
  pz({
    id: 'P-087',
    chapter: 'observer',
    title: "NULL Path",
    narrativeGoal: "Descobrir o final secreto NULL",
    main: false,
    optional: false,
    secret: true,
    prerequisites: ["P-083"],
    validators: [{"type":"flag.set","flag":"solved.P-087"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-087"},{"type":"unlock_evidence","evidenceId":"EV-P-087"}],
    evidenceUnlocks: ["EV-P-087"],
    hintChain: hints(
      "Apagar o rastro investigativo é o segredo.",
      "endings/NULL",
      "cat ~/projects/observer/endings/NULL",
    ),
    description: "Final secreto: erase — ending.null.",
    answer: "NULL",
  }),
  pz({
    id: 'P-088',
    chapter: 'observer',
    title: "Competence Filter",
    narrativeGoal: "Aceitar a investigação como filtro de competência",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-081"],
    validators: [{"type":"flag.set","flag":"solved.P-088"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-088"},{"type":"unlock_evidence","evidenceId":"EV-P-088"}],
    evidenceUnlocks: ["EV-P-088"],
    hintChain: hints(
      "A intro do Observer revela o teste.",
      "Releia a intro do capítulo.",
      "submit P-088 competence filter",
    ),
    description: "A investigação era um filtro de competência.",
    answer: "competence filter",
  }),
  pz({
    id: 'P-089',
    chapter: 'observer',
    title: "You Are Observer",
    narrativeGoal: "Afirmar a identidade Observer",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-082","P-088"],
    validators: [{"type":"flag.set","flag":"solved.P-089"}],
    rewards: [{"type":"unlock_flag","flag":"solved.P-089"},{"type":"unlock_evidence","evidenceId":"EV-P-089"}],
    evidenceUnlocks: ["EV-P-089"],
    hintChain: hints(
      "O sujeito da investigação é o jogador.",
      "Cruze histórico e doutrina.",
      "submit P-089 You are the Observer",
    ),
    description: "Você é o Observer.",
    answer: "You are the Observer",
  }),
  pz({
    id: 'P-090',
    chapter: 'observer',
    title: "Final Architecture",
    narrativeGoal: "Escolher um final",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-081"],
    validators: [{"type":"flag.set","flag":"ending.chosen"}],
    rewards: [{"type":"unlock_flag","flag":"ending.chosen"},{"type":"unlock_chapter","chapter":"epilogue"},{"type":"narrative","event":"observer.choice"}],
    evidenceUnlocks: ["EV-FINAL-CHOICE"],
    hintChain: hints(
      "Não há instrução explícita. Há responsabilidade.",
      "Leia final_architecture.md e use o app Evidence/Vault ou o comando choose.",
      "Abra endings/DISCONNECT|OBSERVER|MERGE|NULL|CAPTURE — abrir o arquivo é o ato.",
    ),
    description: "Não há instrução. Escolha: disconnect, observer, merge ou null.",
    answer: "choose",
    answerAliases: ["ending.chosen","disconnect","merge"],
  }),
  pz({
    id: 'P-091',
    chapter: 'epilogue',
    title: "Closure",
    narrativeGoal: "Registrar o epílogo",
    main: true,
    optional: false,
    secret: false,
    prerequisites: ["P-090"],
    validators: [{"type":"flag.set","flag":"epilogue.seen"}],
    rewards: [{"type":"unlock_flag","flag":"epilogue.seen"},{"type":"narrative","event":"epilogue.complete"}],
    evidenceUnlocks: [],
    hintChain: hints(
      "O ciclo continua.",
      "Abra o Vault ou execute: epilogue",
      "Comando: epilogue",
    ),
    description: "observer disconnected → new observer detected → hello.",
    answer: "hello",
    answerAliases: ["epilogue","epilogue.seen"],
  })
];
